[package]
name = "led_button_interrupt"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "led_button_interrupt"
test = false
doctest = false 
bench = false

[dependencies]
cortex-m-rt = "0.7.5"
stm32f3 = { version = "0.16.0", features = ["stm32f303"] }
