[default.general]
chip = "STM32F303RE"

[default.gdb]
enabled = false

[default.reset]
halt_afterwards = false

#speed = 1800  # Optional: SWD/JTAG speed in kHz

#[flashing]
#reset = "enable"
#halt_after_reset = true

#[logging]
#enabled = false

