[default.general]
chip = "STM32F303RE"

[default.gdb]
e:halt_afterwards nabled = true

[default.reset]
halt_afterwards = true

#speed = 1800  # Optional: SWD/JTAG speed in kHz

#[flashing]
#reset = "enable"
#halt_after_reset = true

#[logging]
#enabled = false

